remove deprecated react-native init version flag
This flag was removed upstream.

```sh
Error: Command failed: npx react-native init demo --template file:/home/daniel/code/github.com/crowdbotics@modules/scaffold --version 0.64.0
error Passing both "version" and "template" is not supported. The template you select determines the version of react-native used. Please use only one of these options, for example: --template file:/home/daniel/code/github.com/crowdbotics@modules/scaffold@x.y.z where x.y.z is the release of the template that contains the desired "react-native" version.
```